services:
  sunset-house:
    image: 242912/sunset-house:latest
    container_name: sunset-house
    env_file:
      - .env
    environment:
      CONTENTFUL_GRAPHQL_ENDPOINT: ${CONTENTFUL_GRAPHQL_ENDPOINT}
      CONTENTFUL_ACCESS_TOKEN: ${CONTENTFUL_ACCESS_TOKEN}
      CONTENTFUL_SPACE_ID: ${CONTENTFUL_SPACE_ID}
      CONTENTFUL_REVALIDATE_SECRET: ${CONTENTFUL_REVALIDATE_SECRET}
      PORT: 5000
    volumes:
      - ./.env.production:/app/.env
    restart: always
    ports:
      - 5000:5000
